# Generated by Django 4.2.14 on 2024-07-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anmeldung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('name_kapitaen', models.CharField(max_length=50)),
                ('anmeldedatum', models.DateTimeField(auto_now_add=True)),
                ('dummy', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
