# Generated by Django 4.2.14 on 2024-07-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teilnehmer',
            name='dummy',
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='name_kapitaen',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='teamname',
            field=models.CharField(max_length=25),
        ),
    ]
