# Generated by Django 4.2.14 on 2024-07-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0003_remove_teilnehmer_dummy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='handy_nr',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
