# Generated by Django 4.2.23 on 2025-07-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0004_teilnehmer_handy_nr'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBoxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_mode', models.CharField(choices=[('standard', 'Standard Turnier Info'), ('cancelled', 'Turnier Absage'), ('custom', 'Benutzerdefiniert')], default='standard', max_length=20, verbose_name='Aktiver Modus')),
                ('standard_title', models.CharField(default='Info', max_length=100, verbose_name='Standard: Titel')),
                ('standard_date', models.CharField(default='Samstag, 26.07.2025', max_length=100, verbose_name='Standard: Datum')),
                ('standard_fee', models.CharField(default='10€ Startgebühr', max_length=100, verbose_name='Standard: Startgebühr')),
                ('standard_location', models.CharField(default='Am Starzenbach, 82340 Feldafing', max_length=200, verbose_name='Standard: Ort')),
                ('standard_team_info', models.CharField(default='4+1 Spieler Pro Team', max_length=100, verbose_name='Standard: Team Info')),
                ('standard_contact', models.TextField(default='Fragen?\n-> +49 176 8513 1778', verbose_name='Standard: Kontakt')),
                ('cancelled_title', models.CharField(default='Turnier Absage', max_length=100, verbose_name='Absage: Titel')),
                ('cancelled_message', models.TextField(default='Dieses Jahr findet das Dorfturnier leider nicht statt aufgrund zu wenig Anmeldungen.\n\nWir hoffen auf nächstes Jahr!', verbose_name='Absage: Nachricht')),
                ('cancelled_contact', models.TextField(default='Fragen?\n-> +49 176 8513 1778', verbose_name='Absage: Kontakt')),
                ('custom_title', models.CharField(default='Info', max_length=100, verbose_name='Custom: Titel')),
                ('custom_content', models.TextField(default='Hier kann beliebiger Inhalt stehen.', help_text='HTML-Tags sind erlaubt. Zeilenumbrüche mit <br> erstellen.', verbose_name='Custom: Inhalt')),
                ('show_registration_form', models.BooleanField(default=True, help_text='Wenn deaktiviert, wird nur die Info-Box angezeigt', verbose_name='Anmeldeformular anzeigen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info-Box Konfiguration',
                'verbose_name_plural': 'Info-Box Konfiguration',
            },
        ),
    ]
